bundle: gla
excluded:
  - core.entity_form_display.node.article.default
  - core.entity_view_display.node.article.default
  - core.entity_view_display.node.article.rss
  - core.entity_view_display.node.article.teaser
  - field.field.node.article.body
  - field.field.node.article.comment
  - field.field.node.article.field_image
  - field.field.node.article.field_tags
  - field.storage.node.comment
  - field.storage.node.field_tags
required: true
